### ISSUE TITLE
config option redirect_non_whitelisted_to seems not working

### ISSUE THREAD

**Issue by rajanrawal** [antonioribeiro/firewall#12]
Hi I have mentioned route for redirect_non_whitelisted_to like

redirect_non_whitelisted_to => 'coming/soon' and created same route as well, but filter does not redirect it to desired route, rather it returns with values mentioned in following option

    'block_response_code' => 403,

    'block_response_message' => 'You are not authorized',

By Filter files came to know that only Whitelist.php filter uses redirect_non_whitelisted_to and not Blacklist.php am i right or Am I doing something wrong?

**Comment by ridesoft** [comment]
I used this:
```
'redirect_non_whitelisted_to' => '/403',
```
and for me it works.
try to add a slash in the route

**Comment by rajanrawal** [comment]
I used same as in example
'redirect_non_whitelisted_to' => '/coming/soon' but its not working.

Redirection code is there in black list filter but not in white list
filter. May be I'm mistaken somewhere.

**Comment by antonioribeiro** [comment]
Sorry for the delay. Tested it now and it works fine.
I'm doing some changes on it too, you will be able to use named routes on it too:

    'redirect_non_whitelisted_to' => 'coming.soon'

Already in master, will try to tag a version tomorrow.

**Comment by rajanrawal** [comment]
@antonioribeiro thank you.
Just to know, was is really missing? Because ` 'redirect_non_whitelisted_to' => 'some_route'` was already there but was not working. rather `block_response_code` and `block_response_message` were only working fine.

**Comment by antonioribeiro** [comment]
@rajanrawal, it was already ok, but for it to work you only need 2 things:

1) A whitelist blocked route:

    Route::group(['before' => 'fw-allow-wl'], function()
    {
        Route::get('/', 'HomeController@showWelcome');
    });

You will only be able to hit if the client IP address is in a whitelist.

2) An alternative route (obvious :)

    Route::get('coming/soon', ['as' => 'coming.soon', 'uses' => 'HomeController@showComingSoon']);

Note that a whitelist blocked route will not use block_response_code and block_response_message, if those guys were being used is because you were hitting a blacklisted route.

**Comment by antonioribeiro** [comment]
Sorry, I have to correct myself. If the client IP is not in the white list AND you don't have a redirect_non_whitelisted_to configured it will be blocked and use block_response_code and block_response_message.

**Comment by antonioribeiro** [comment]
Closing for now. If you have any more troubles, please ping me on IRC (#laravel).

**Comment by saimiris** [comment]
Hi there, I am a senior Laravel developer and I use your excellent plugin since many years for my testing environment. 
I realized since very few that the "redirect_non_whitelisted_to" is NOT working properly.
For the blacklisted routes, I just get a blank page with no code and no message, while it should redirect to the route I have defined in the configuration file.
