### ISSUE TITLE
Firewall Facade not found

### ISSUE THREAD

**Issue by enprixd** [antonioribeiro/firewall#32]
Currently using Laravel 5.1.

Can't use any of the static methods in the Firewall Facade, generally because it seems that the facade can't be seen.

And the service provider and aliases have been properly configured.

![image](https://cloud.githubusercontent.com/assets/5968230/8976059/1c1026c6-36ba-11e5-99a7-23fabb1bd63b.png)

![image](https://cloud.githubusercontent.com/assets/5968230/8976075/6563e5ec-36ba-11e5-9df4-dd27838bca74.png)

I tried to rule out the possibility that it only conflicts with some of my packages so I tried it on a fresh install of laravel 5.1

![image](https://cloud.githubusercontent.com/assets/5968230/8976518/a9848c12-36c0-11e5-899a-7a5fb222976e.png)

And so, as of writing, I realize that it might be because it doesn't support 5.1 yet?

**Comment by bebnev** [comment]
The problem is in your use statement.
```php
use PragmaRX\Firewall\Vendor\Laravel\Facade;
```
It means that you are going to use Facade class, not Firewall class.
To import Firewall class you can do it like this
```php
use PragmaRX\Firewall\Vendor\Laravel\Facade as Firewall;
```
or in Laravel style (which is more preferable from my point of view):
```php
use Firewall;
```

I have just installed fresh Laravel 5.1 install with that package and it seem to be working.

**Comment by enprixd** [comment]
Ohhh. I totally forgot about that.

I should've checked first.

I thought simply creating the alias would instantly allow Firewall. Would be awesome if Facade is actually named Firewall tho. 

Thanks.

But yeah. I'm gonna close this.

**Comment by enprixd** [comment]
Erm. But isn't that the point of adding `'Firewall'  => PragmaRX\Firewall\Vendor\Laravel\Facade::class,` to my `app.php` config?

There might be a conflict somewhere here. I'm using PHP Storm, and it couldn't find the Firewall Facade. 

It could easily point to other Facades but it points me to the wrong classes when I try to import automatically.

Hmmm. But, okay.

As long as it works, it's fine, I guess.

**Comment by bebnev** [comment]
```php
'Firewall' => PragmaRX\Firewall\Vendor\Laravel\Facade::class
```
in your app.php config means that you tell autoloader to create a short alias (in lazy load mode) for the PragmaRX\Firewall\Vendor\Laravel\Facade class, so in your app you can point to 
```php
use Firewall; //or any other alias name that you used in alias section
```
and not to the full class name.
Autoimport point to the wrong class because the package has no facade class with the name of Firewall. Many packages use such convention for the facades name: /path/to/package/Facade/Firewall.php (for example), but here the author of the package decided to use another name for the facade.
So autoimport suggests me only 

![firewall-autoimport](https://cloud.githubusercontent.com/assets/8371521/8978969/bf4a9554-36b7-11e5-804d-8212869e9901.png)

When you use aliases, PhpStorm will not find the classes because he has no idea that you are using an alias for the class, but even if he knows about it, he will point to facade class that realy has nothing except getFacadeAccessor static method. If you would like PhpStrom make autocomple for such Facades have a look at [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)

**Comment by enprixd** [comment]
Yeah. I'd have to use ide-helper for this instance. Thanks.
